return {
	"xiyaowong/transparent.nvim",
	lazy = false,
	config = function()
		require("transparent").setup({
			groups = { -- Default groups
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"NonText",
				"SignColumn",
				"CursorLine",
				"CursorLineNr",
				"StatusLine",
				"StatusLineNC",
				"EndOfBuffer",
			},
			extra_groups = {
				-- Add bufferline-specific highlight groups
				"BufferLineBackground",
				"BufferLineFill",
				"BufferLineSeparator",
				"BufferLineSeparatorSelected",
				"BufferLineSeparatorVisible",
				"BufferLineIndicatorSelected",
				"BufferLineModifiedSelected",
				"BufferLineBufferVisible",
				"BufferLineDevIcon*",
				"BufferLineOffset",
				"Tabline",
				"TabLineSel",
				"TabLineFill",
			},
			exclude_groups = {
				"NormalFloat",
			},
		})
	end,
}
